# Generated by Django 2.0.6 on 2018-06-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gouging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_material', models.PositiveIntegerField(verbose_name='Количество затраченного материала')),
                ('spent_time', models.TimeField(verbose_name='Затраченное время')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала строжки')),
            ],
        ),
        migrations.CreateModel(
            name='HeatTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_oven', models.TimeField(verbose_name='Время в печи')),
                ('final_hardness', models.PositiveIntegerField(verbose_name='Итоговая твердость')),
                ('start_date', models.DateTimeField(verbose_name='Дата погрузки в печь')),
            ],
        ),
        migrations.CreateModel(
            name='Machining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала работы')),
                ('machine_time', models.TimeField(verbose_name='Время работы станка')),
            ],
        ),
        migrations.CreateModel(
            name='MainFormTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер оснастки')),
                ('letter', models.CharField(max_length=1, verbose_name='Литера')),
                ('received_stamp_date', models.DateTimeField(verbose_name='Дата поступления штампа')),
                ('customer', models.CharField(max_length=128, verbose_name='Заказчик')),
                ('scheme', models.BooleanField(verbose_name='Чертёж')),
                ('first_heat_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_heat_treatment', to='IS.HeatTreatment', verbose_name='Первичная термообработка')),
                ('gouging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.Gouging', verbose_name='Строжка')),
                ('machining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.Machining', verbose_name='Механообработка')),
                ('second_heat_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_heat_treatment', to='IS.HeatTreatment', verbose_name='Вторичная термообработка')),
            ],
        ),
        migrations.CreateModel(
            name='Surfacing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_material', models.PositiveIntegerField(verbose_name='Количество наплавленного')),
                ('type_of_consumables', models.CharField(max_length=50, verbose_name='Тип расходника')),
                ('robot_work_time', models.TimeField(verbose_name='Время работы робота')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала наплавки')),
            ],
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
        migrations.AddField(
            model_name='mainformtable',
            name='surfacing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.Surfacing', verbose_name='Наплавка'),
        ),
    ]
