image: python:3.6.1

pipelines:
  parallel:
    - step:
        name: autopep8
        caches:
          - pip
        script:
          - echo 'Clone all the things!'
          - pip install autopep8
          - autopep8 --aggressive --aggressive -r -d *
    - step:
        name: testing...
        script:
          - python3 -m unittest discover tests/
